version: "2.39.2"

volumes:
  postgres-data-storage:
  redis-data-storage:
  minio-data-storage:

services:
  cloudfilestorage:
    build: .
    container_name: cloudfilestorage
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      AWS_REGION: eu-central-1
      AWS_ACCESSKEYID: minioadmin
      AWS_SECRETKEY: minioadmin
      AWS_S3_BUCKET: cloudfilestorage
      AWS_S3_ENDPOINT: http://minio:9000
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-storage:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data-storage:/data
    command: ["redis-server", "--appendonly", "yes"]

  minio:
    image: minio/minio
    container_name: minio-storage
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data-storage:/data

